// <auto-generated />
using System;
using DohunKim.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DohunKim.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211101191703_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Do4.Models.Project_Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorName");

                    b.HasIndex("ProjectName");

                    b.ToTable("Project_Authors");
                });

            modelBuilder.Entity("Do4.Models.Project_Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageName");

                    b.HasIndex("ProjectName");

                    b.ToTable("Project_Languages");
                });

            modelBuilder.Entity("DohunKim.Models.ApplicationType", b =>
                {
                    b.Property<string>("TypeName")
                        .HasColumnType("TEXT");

                    b.HasKey("TypeName");

                    b.ToTable("ApplicationType");

                    b.HasData(
                        new
                        {
                            TypeName = "Mobile Application"
                        },
                        new
                        {
                            TypeName = "Web Application"
                        },
                        new
                        {
                            TypeName = "RESTful API"
                        },
                        new
                        {
                            TypeName = "iOS Application"
                        },
                        new
                        {
                            TypeName = "Android Application"
                        },
                        new
                        {
                            TypeName = "Chrome Extension"
                        });
                });

            modelBuilder.Entity("DohunKim.Models.Author", b =>
                {
                    b.Property<string>("AuthorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorName");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("DohunKim.Models.Language", b =>
                {
                    b.Property<string>("LanguageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.HasKey("LanguageName");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("DohunKim.Models.Occupation", b =>
                {
                    b.Property<string>("OccupationTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .HasColumnType("TEXT");

                    b.HasKey("OccupationTitle");

                    b.HasIndex("AuthorName");

                    b.ToTable("Occupations");
                });

            modelBuilder.Entity("DohunKim.Models.Project", b =>
                {
                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("GithubURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectDesc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectName");

                    b.HasIndex("TypeName");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectName = "uTrack",
                            DemoURL = "",
                            GithubURL = "",
                            ProjectDesc = "",
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeName = "Web Application"
                        },
                        new
                        {
                            ProjectName = "The Mindful Shopper",
                            DemoURL = "",
                            GithubURL = "",
                            ProjectDesc = "",
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeName = "Chrome Extension"
                        },
                        new
                        {
                            ProjectName = "TI Project",
                            DemoURL = "",
                            GithubURL = "",
                            ProjectDesc = "RESTful API",
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProjectName = "Mealo-Box",
                            DemoURL = "",
                            GithubURL = "",
                            ProjectDesc = "Mobile Application",
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Do4.Models.Project_Author", b =>
                {
                    b.HasOne("DohunKim.Models.Author", "Author")
                        .WithMany("Project_Authors")
                        .HasForeignKey("AuthorName");

                    b.HasOne("DohunKim.Models.Project", "Project")
                        .WithMany("Project_Authors")
                        .HasForeignKey("ProjectName");

                    b.Navigation("Author");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Do4.Models.Project_Language", b =>
                {
                    b.HasOne("DohunKim.Models.Language", "Language")
                        .WithMany("Project_Languages")
                        .HasForeignKey("LanguageName");

                    b.HasOne("DohunKim.Models.Project", "Project")
                        .WithMany("Project_Languages")
                        .HasForeignKey("ProjectName");

                    b.Navigation("Language");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DohunKim.Models.Occupation", b =>
                {
                    b.HasOne("DohunKim.Models.Author", "Author")
                        .WithMany("Occupations")
                        .HasForeignKey("AuthorName");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("DohunKim.Models.Project", b =>
                {
                    b.HasOne("DohunKim.Models.ApplicationType", "ApplicationType")
                        .WithMany("Projects")
                        .HasForeignKey("TypeName");

                    b.Navigation("ApplicationType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DohunKim.Models.ApplicationType", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("DohunKim.Models.Author", b =>
                {
                    b.Navigation("Occupations");

                    b.Navigation("Project_Authors");
                });

            modelBuilder.Entity("DohunKim.Models.Language", b =>
                {
                    b.Navigation("Project_Languages");
                });

            modelBuilder.Entity("DohunKim.Models.Project", b =>
                {
                    b.Navigation("Project_Authors");

                    b.Navigation("Project_Languages");
                });
#pragma warning restore 612, 618
        }
    }
}
